/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebaconeccion;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nelson
 */
public class NewJFrame extends javax.swing.JFrame {
JTable tabla;
ResultSet rs;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        IniciarTabla();
        
     
      // ingreso al githup      
      
    }
    
    
    // Carga la tabla del inicio y cada vez que es llamado el Objeto listando todos los elementos de la tabla comuna
    private void IniciarTabla(){
        
        // limpia los datos de los Label y los datos relacionados a la actualizacion de los datos e inhabilita y habilitar botones
this.jLabelId.setText("Id");
this.jnombre.setText("");
grabarCambios.setEnabled(false);
jBotonAgregar.setEnabled(true);

    DefaultTableModel dfm = new DefaultTableModel();
        tabla = this.jTabla;
        tabla.setModel(dfm);
        
        // agrega los datos al index de la tabla 
        dfm.setColumnIdentifiers(new Object[]{"id","Comuna","Estado"});
        Conexion cn = new Conexion();
       rs = cn.SeleccionarTodosComunas();
       try{
           // se recorre rs donde estan los resultados de la busqueda de los datos de la tabla comuna
       while(rs.next()){
           String activo ="";
           if (rs.getInt("COM_ESTADO")==1) {
               activo = "activo";
                       } else {
               activo = "no activo";};
           // se agrega la fila con los datos de la columna         
       dfm.addRow(new Object[]{rs.getInt("COM_ID"),rs.getString("COM_NOMBRE"),activo});
       }
       
       } catch(Exception e){
       System.out.println("Error Revisar funcion TableModel" + e);
       }
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jnombre = new javax.swing.JTextField();
        jBotonAgregar = new javax.swing.JButton();
        jactivo = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        grabarCambios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextBuscar = new javax.swing.JTextField();
        jBuscar = new javax.swing.JButton();
        jListarComunas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Comuna");

        jBotonAgregar.setText("Agregar Nuevo");
        jBotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAgregarActionPerformed(evt);
            }
        });

        jactivo.setSelected(true);
        jactivo.setText("Activo");
        jactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jactivoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMINISTRADOR DE COMUNAS");

        jLabelId.setText("Id");

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabla);
        if (jTabla.getColumnModel().getColumnCount() > 0) {
            jTabla.getColumnModel().getColumn(0).setResizable(false);
            jTabla.getColumnModel().getColumn(1).setResizable(false);
            jTabla.getColumnModel().getColumn(2).setResizable(false);
            jTabla.getColumnModel().getColumn(3).setResizable(false);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        grabarCambios.setText("Grabar cambios");
        grabarCambios.setEnabled(false);
        grabarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarCambiosActionPerformed(evt);
            }
        });

        jLabel3.setText("Buscardor");

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jListarComunas.setText("Todas las Comunas");
        jListarComunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListarComunasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabelId)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBotonAgregar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jactivo)
                        .addGap(26, 26, 26)
                        .addComponent(grabarCambios)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jListarComunas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBuscar)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(49, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jactivo)
                    .addComponent(jnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelId)
                    .addComponent(grabarCambios))
                .addGap(42, 42, 42)
                .addComponent(jBotonAgregar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscar)
                    .addComponent(jListarComunas))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Boton Agregar Nuevo
    private void jBotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAgregarActionPerformed
        // TODO add your handling code here:
        if (this.jnombre.getText().length()!=0){  // validar que jnombre no este vacio
           // otro comentario 
            String nombre = this.jnombre.getText();
        boolean activo = this.jactivo.isSelected();
        int tipo = 0;
        if (activo==true) {
            tipo=1;
        }
        JOptionPane.showMessageDialog(rootPane, "Comuna Ingresada"); // agregar mensaje
        this.jnombre.setText("");
        this.jactivo.isSelected(); // error falta marcar el select ()
         
        Conexion cn = new Conexion();
        cn.InsertarDatos(nombre,tipo);
        
        IniciarTabla();
        
        
        
        
        
        
        } else {
            
            
          JOptionPane.showMessageDialog(rootPane, "Tiene que ingresar datos"); // agregar mensaje  
            
            
        
    }//GEN-LAST:event_jBotonAgregarActionPerformed
    }
    private void grabarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarCambiosActionPerformed

        if (this.jnombre.getText().length()!=0){  // validar que no ingresen datos vacios
            
        
 int id = Integer.parseInt(this.jLabelId.getText());
String comuna = this.jnombre.getText();
boolean estado = this.jactivo.isSelected();
        int tipo = 0;
        if (estado==true) {
            tipo=1;
        }
        
        Conexion cn = new Conexion();
        cn.EditarDatos(id,comuna,tipo);

JOptionPane.showMessageDialog(rootPane, "Comuna Modificada"); // agregar mensaje
IniciarTabla();
this.jLabelId.setText("Id");
this.jnombre.setText("");
grabarCambios.setEnabled(false);
jBotonAgregar.setEnabled(true);
        // TODO add your handling code here:
        } else {
        JOptionPane.showMessageDialog(rootPane, "Tiene que ingresar datos"); // agregar mensaje  
          
        }
        
    }//GEN-LAST:event_grabarCambiosActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
this.jLabelId.setText("Id");
this.jnombre.setText("");
grabarCambios.setEnabled(false);
   jBotonAgregar.setEnabled(true);     
String activo ="";
String comuna = this.jTextBuscar.getText().toString();
Conexion cn = new Conexion();
ResultSet rs = cn.SeleccionarLaComunas(comuna);
DefaultTableModel dfmbuscar = new DefaultTableModel();
this.jTabla.setModel(dfmbuscar);
dfmbuscar.setColumnIdentifiers(new Object[]{"ID","Comuna","Estado"});
try{
   while(rs.next()){ 
      activo ="";
           if (rs.getInt("COM_ESTADO")==1) {
               activo = "activo";
                       } else {
               activo = "no activo";};
                   
       dfmbuscar.addRow(new Object[]{rs.getInt("COM_ID"),rs.getString("COM_NOMBRE"),activo});
}
}catch(Exception e){
       System.out.println("Error Revisar funcion Buscar TableModel" + e);
       }
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jListarComunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarComunasActionPerformed
        // TODO add your handling code here:
        IniciarTabla();
       
        
        
        
    }//GEN-LAST:event_jListarComunasActionPerformed

    private void jTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaMouseClicked
jBotonAgregar.setEnabled(false);
int Fila = jTabla.getSelectedRow();
String id = jTabla.getValueAt(Fila, 0).toString();
String comuna = jTabla.getValueAt(Fila, 1).toString();
String estado = jTabla.getValueAt(Fila, 2).toString();


// llenar los datos de textfield
this.jLabelId.setText(id);
this.jnombre.setText(comuna);
this.jactivo.setText(estado);

if (estado == "activo"){
    this.jactivo.setSelected(true);
    
} else { this.jactivo.setSelected(false);   
}

grabarCambios.setEnabled(true);
System.out.println("id :"+id+"comuna :"+comuna+"estado :"+estado);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablaMouseClicked

    private void jactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jactivoActionPerformed

// Cambiar nombre al click activo o inactivo

if( !this.jactivo.isSelected()){ this.jactivo.setText("no activo");     
} else {
   this.jactivo.setText("activo");
            
    }



    }//GEN-LAST:event_jactivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton grabarCambios;
    private javax.swing.JButton jBotonAgregar;
    private javax.swing.JButton jBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JButton jListarComunas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabla;
    private javax.swing.JTextField jTextBuscar;
    private javax.swing.JCheckBox jactivo;
    private javax.swing.JTextField jnombre;
    // End of variables declaration//GEN-END:variables

    
}
